import { User } from "@/types/auth";
import { Doctor, MicrobiomeReport, Patient } from "@/types/microbiome";

export const MOCK_USERS: (User & { password: string })[] = [
  {
    id: "usr_101",
    name: "Dra. Elena Ramos",
    email: "doctor@microbioma.com",
    password: "password123",
    role: "doctor",
  },
  {
    id: "usr_102",
    name: "María García",
    email: "paciente@microbioma.com",
    password: "password123",
    role: "paciente",
    patientId: "PAT-88219",
  },
  {
    id: "usr_103",
    name: "Clínica Bionova Health",
    email: "clinica@microbioma.com",
    password: "password123",
    role: "clinica",
  },
];

export const MOCK_DOCTORS: Doctor[] = [
  {
    id: "doc_01",
    userId: "usr_101",
    clinicId: "cli_01",
    name: "Dra. Elena Ramos",
    specialty: "Gastroenterología",
  },
  {
    id: "doc_02",
    userId: "usr_104",
    clinicId: "cli_01",
    name: "Dr. Pablo Iturralde",
    specialty: "Nutrición Clínica",
  },
];

export const MOCK_PATIENTS: Patient[] = [
  {
    id: "PAT-88219",
    userId: "usr_102",
    doctorId: "doc_01",
    name: "María García",
    age: 34,
    gender: "F",
    lastAnalysisDate: "2026-08-20",
    dysbiosisLevel: "LEVE",
    status: "PENDIENTE",
  },
  {
    id: "PAT-77103",
    doctorId: "doc_01",
    name: "Carlos Ruiz",
    age: 47,
    gender: "M",
    lastAnalysisDate: "2026-08-22",
    dysbiosisLevel: "SEVERO",
    status: "PROCESANDO",
  },
  {
    id: "PAT-65012",
    doctorId: "doc_01",
    name: "Elena Gómez",
    age: 29,
    gender: "F",
    lastAnalysisDate: "2026-08-15",
    dysbiosisLevel: "OPTIMO",
    status: "PUBLICADO",
  },
  {
    id: "PAT-90341",
    doctorId: "doc_01",
    name: "Javier Torres",
    age: 52,
    gender: "M",
    lastAnalysisDate: "2026-08-23",
    status: "SOLICITADO",
  },
  {
    id: "PAT-55210",
    doctorId: "doc_02",
    name: "Lucía Fernández",
    age: 41,
    gender: "F",
    lastAnalysisDate: "2026-08-10",
    dysbiosisLevel: "LEVE",
    status: "PUBLICADO",
  },
  {
    id: "PAT-30987",
    doctorId: null,
    name: "Roberto Sánchez",
    age: 38,
    gender: "M",
  },
];

export const MOCK_REPORTS: MicrobiomeReport[] = [
  {
    id: "rep_001",
    patientId: "PAT-88219",
    trackingCode: "TRK-2026-0891",
    patientName: "María García",
    analysisDate: "2026-08-20",
    diversityIndex: 6.4,
    dysbiosisLevel: "LEVE",
    status: "PENDIENTE",
    biomarkers: [
      {
        id: "b1",
        reportId: "rep_001",
        name: "Akkermansia muciniphila",
        category: "Integridad Mucosa",
        currentValue: 3.2,
        minReference: 1.0,
        maxReference: 4.0,
        unit: "%",
        status: "NORMAL",
      },
      {
        id: "b2",
        reportId: "rep_001",
        name: "Faecalibacterium prausnitzii",
        category: "Productores de Butirato",
        currentValue: 0.4,
        minReference: 2.5,
        maxReference: 8.0,
        unit: "%",
        status: "BAJO",
      },
      {
        id: "b3",
        reportId: "rep_001",
        name: "Escherichia coli",
        category: "Potenciales Patobiontes",
        currentValue: 5.8,
        minReference: 0.0,
        maxReference: 1.5,
        unit: "log10",
        status: "ALTO",
      },
    ],
    actionPlan: [
      {
        id: "ap1",
        reportId: "rep_001",
        category: "NUTRICION",
        title: "Fibra prebiótica",
        description: "Aumentar ingesta de alcachofas, avena y plátano verde.",
        priority: "ALTA",
      },
      {
        id: "ap2",
        reportId: "rep_001",
        category: "SUPLEMENTACION",
        title: "Butirato de sodio",
        description: "500mg/día durante 6 semanas para soporte de mucosa intestinal.",
        priority: "MODERADA",
      },
      {
        id: "ap3",
        reportId: "rep_001",
        category: "LIFESTYLE",
        title: "Reducir ultraprocesados",
        description: "Evitar azúcares refinados y grasas trans durante el protocolo.",
        priority: "ALTA",
      },
    ],
  },
  {
    id: "rep_005",
    patientId: "PAT-88219",
    trackingCode: "TRK-2026-0750",
    patientName: "María García",
    analysisDate: "2026-05-10",
    diversityIndex: 5.2,
    dysbiosisLevel: "LEVE",
    status: "PUBLICADO",
    biomarkers: [
      {
        id: "b0",
        reportId: "rep_005",
        name: "Faecalibacterium prausnitzii",
        category: "Productores de Butirato",
        currentValue: 1.1,
        minReference: 2.5,
        maxReference: 8.0,
        unit: "%",
        status: "BAJO",
      },
    ],
    actionPlan: [
      {
        id: "ap0",
        reportId: "rep_005",
        category: "NUTRICION",
        title: "Fibra fermentable",
        description: "Incluir avena, legumbres y plátano verde a diario.",
        priority: "ALTA",
      },
      {
        id: "ap0b",
        reportId: "rep_005",
        category: "LIFESTYLE",
        title: "Higiene del sueño",
        description: "Mantener 7-8h de sueño para favorecer la diversidad microbiana.",
        priority: "MODERADA",
      },
    ],
  },
  {
    id: "rep_002",
    patientId: "PAT-77103",
    trackingCode: "TRK-2026-0892",
    patientName: "Carlos Ruiz",
    analysisDate: "2026-08-22",
    diversityIndex: 3.1,
    dysbiosisLevel: "SEVERO",
    status: "PROCESANDO",
    biomarkers: [
      {
        id: "b4",
        reportId: "rep_002",
        name: "Bacteroides fragilis",
        category: "Potenciales Patobiontes",
        currentValue: 9.4,
        minReference: 0.0,
        maxReference: 2.0,
        unit: "log10",
        status: "ALTO",
      },
    ],
    actionPlan: [],
  },
  {
    id: "rep_003",
    patientId: "PAT-65012",
    trackingCode: "TRK-2026-0893",
    patientName: "Elena Gómez",
    analysisDate: "2026-08-15",
    diversityIndex: 8.1,
    dysbiosisLevel: "OPTIMO",
    status: "PUBLICADO",
    biomarkers: [
      {
        id: "b5",
        reportId: "rep_003",
        name: "Akkermansia muciniphila",
        category: "Integridad Mucosa",
        currentValue: 3.0,
        minReference: 1.0,
        maxReference: 4.0,
        unit: "%",
        status: "NORMAL",
      },
    ],
    actionPlan: [
      {
        id: "ap4",
        reportId: "rep_003",
        category: "NUTRICION",
        title: "Mantenimiento",
        description: "Continuar con dieta rica en fibra variada.",
        priority: "BAJA",
      },
    ],
  },
  {
    id: "rep_004",
    patientId: "PAT-90341",
    trackingCode: "TRK-2026-0894",
    patientName: "Javier Torres",
    analysisDate: "2026-08-23",
    diversityIndex: 0,
    dysbiosisLevel: "LEVE",
    status: "SOLICITADO",
    biomarkers: [],
    actionPlan: [],
  },
];